name: Build and deploy base docker image for dagster's fast deployments.
run-name: ${{ github.actor }} is building docker image
on: 
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: project-repo

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and push to temporary local registry 
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:docker"
          push: true
          tags: localhost:5000/test-image:temporary

      - name: Inspect docker image
        run: docker buildx imagetools inspect localhost:5000/test-image:temporary

      - name: Pull the image to local docker storage
        run: docker pull localhost:5000/test-image:temporary

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Dockerfile contents in this release:
            $(cat docker/Dockerfile)
          draft: false
          prerelease: false
      - name: Print Published Tag
        run: |
          echo "Put the following tag in the 'dagster' repo, branch_deployments.yml SERVERLESS_BASE_IMAGE_TAG"
          echo "to test out your base docker image in staging:"
          echo "SERVERLESS_BASE_IMAGE_TAG = 'test-image_${{ github.ref }}'"

