# Builds a docker image to use for dagster fast deployments
# This script will build & deploy an image to dagster cloud
# on PR merge to main

name: Build and deploy base docker image for dagster's fast deployments.
run-name: ${{ github.actor }} is building docker image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: project-repo

      - name: Print Published Tag
        run: |
          echo "Put the following tag in the 'dagster' repo, branch_deployments.yml SERVERLESS_BASE_IMAGE_TAG"
          echo "to test out your base docker image in staging:"
          echo "SERVERLESS_BASE_IMAGE_TAG = 'cybersyn-dagster-base-image_${{ github.run_number }}'"
          
      - name: Get Dockerfile content
        id: dockerfile_content
        run: |
          echo "$(pwd)"
          echo "$(ls -al)"
          echo "dockerfile_content = $(cat docker/Dockerfile)" >> "$GITHUB_OUTPUT"
          echo "$(cat docker/Dockerfile)"
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Pushed 
            Changes to the Dockerfile:
            ${{ steps.dockerfile_content.outputs.dockerfile_content }}
          draft: false
          prerelease: false
